version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=remcom
      - DB_USER=remcom
      - DB_PASSWORD=remcom
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: remcom
      POSTGRES_USER: remcom
      POSTGRES_PASSWORD: remcom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
